################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
F:/FRI_novSSD/Diploma/Diploma-GitHub/AlgoBuilder/Klasifikacijsko_drevo-Hoja_oseb/projekt/Middlewares/ST/BlueNRG2/hci/controller/bluenrg1_gap_aci.c \
F:/FRI_novSSD/Diploma/Diploma-GitHub/AlgoBuilder/Klasifikacijsko_drevo-Hoja_oseb/projekt/Middlewares/ST/BlueNRG2/hci/controller/bluenrg1_gatt_aci.c \
F:/FRI_novSSD/Diploma/Diploma-GitHub/AlgoBuilder/Klasifikacijsko_drevo-Hoja_oseb/projekt/Middlewares/ST/BlueNRG2/hci/controller/bluenrg1_hal_aci.c \
F:/FRI_novSSD/Diploma/Diploma-GitHub/AlgoBuilder/Klasifikacijsko_drevo-Hoja_oseb/projekt/Middlewares/ST/BlueNRG2/hci/controller/bluenrg1_l2cap_aci.c 

OBJS += \
./Middlewares/BlueNRG2/Controller/bluenrg1_gap_aci.o \
./Middlewares/BlueNRG2/Controller/bluenrg1_gatt_aci.o \
./Middlewares/BlueNRG2/Controller/bluenrg1_hal_aci.o \
./Middlewares/BlueNRG2/Controller/bluenrg1_l2cap_aci.o 

C_DEPS += \
./Middlewares/BlueNRG2/Controller/bluenrg1_gap_aci.d \
./Middlewares/BlueNRG2/Controller/bluenrg1_gatt_aci.d \
./Middlewares/BlueNRG2/Controller/bluenrg1_hal_aci.d \
./Middlewares/BlueNRG2/Controller/bluenrg1_l2cap_aci.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/BlueNRG2/Controller/bluenrg1_gap_aci.o: F:/FRI_novSSD/Diploma/Diploma-GitHub/AlgoBuilder/Klasifikacijsko_drevo-Hoja_oseb/projekt/Middlewares/ST/BlueNRG2/hci/controller/bluenrg1_gap_aci.c Middlewares/BlueNRG2/Controller/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DSTM32L4R9xx -DUSE_HAL_DRIVER -DUSE_USB_FS -DUSE_SENSORTILEBOX -DARM_MATH_CM4 -DUSE_BLE_OUTPUT -c -I../../../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/DSP/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/SensorTile.box -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hh -I../../../../../Drivers/BSP/Components/lsm6dsox -I../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC_MSC/Inc -I../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Inc -I../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../../Middlewares/ST/STM32_MotionAC_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionAW_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionEC_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionGC_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionID_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionMC_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionPM_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionPW_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionTL_Library/Inc -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/ST/BlueNRG2/Utils -I../../../../../Middlewares/ST/BlueNRG2/Controller -I../../../../../Middlewares/ST/BlueNRG2/HCI_TL -I../../../../../Middlewares/ST/BlueNRG2/includes -I"../../../../../Middlewares/ST/BlueNRG2/hci/hci_tl_patterns/Basic" -O3 -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"
Middlewares/BlueNRG2/Controller/bluenrg1_gatt_aci.o: F:/FRI_novSSD/Diploma/Diploma-GitHub/AlgoBuilder/Klasifikacijsko_drevo-Hoja_oseb/projekt/Middlewares/ST/BlueNRG2/hci/controller/bluenrg1_gatt_aci.c Middlewares/BlueNRG2/Controller/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DSTM32L4R9xx -DUSE_HAL_DRIVER -DUSE_USB_FS -DUSE_SENSORTILEBOX -DARM_MATH_CM4 -DUSE_BLE_OUTPUT -c -I../../../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/DSP/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/SensorTile.box -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hh -I../../../../../Drivers/BSP/Components/lsm6dsox -I../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC_MSC/Inc -I../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Inc -I../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../../Middlewares/ST/STM32_MotionAC_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionAW_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionEC_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionGC_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionID_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionMC_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionPM_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionPW_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionTL_Library/Inc -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/ST/BlueNRG2/Utils -I../../../../../Middlewares/ST/BlueNRG2/Controller -I../../../../../Middlewares/ST/BlueNRG2/HCI_TL -I../../../../../Middlewares/ST/BlueNRG2/includes -I"../../../../../Middlewares/ST/BlueNRG2/hci/hci_tl_patterns/Basic" -O3 -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"
Middlewares/BlueNRG2/Controller/bluenrg1_hal_aci.o: F:/FRI_novSSD/Diploma/Diploma-GitHub/AlgoBuilder/Klasifikacijsko_drevo-Hoja_oseb/projekt/Middlewares/ST/BlueNRG2/hci/controller/bluenrg1_hal_aci.c Middlewares/BlueNRG2/Controller/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DSTM32L4R9xx -DUSE_HAL_DRIVER -DUSE_USB_FS -DUSE_SENSORTILEBOX -DARM_MATH_CM4 -DUSE_BLE_OUTPUT -c -I../../../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/DSP/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/SensorTile.box -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hh -I../../../../../Drivers/BSP/Components/lsm6dsox -I../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC_MSC/Inc -I../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Inc -I../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../../Middlewares/ST/STM32_MotionAC_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionAW_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionEC_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionGC_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionID_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionMC_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionPM_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionPW_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionTL_Library/Inc -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/ST/BlueNRG2/Utils -I../../../../../Middlewares/ST/BlueNRG2/Controller -I../../../../../Middlewares/ST/BlueNRG2/HCI_TL -I../../../../../Middlewares/ST/BlueNRG2/includes -I"../../../../../Middlewares/ST/BlueNRG2/hci/hci_tl_patterns/Basic" -O3 -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"
Middlewares/BlueNRG2/Controller/bluenrg1_l2cap_aci.o: F:/FRI_novSSD/Diploma/Diploma-GitHub/AlgoBuilder/Klasifikacijsko_drevo-Hoja_oseb/projekt/Middlewares/ST/BlueNRG2/hci/controller/bluenrg1_l2cap_aci.c Middlewares/BlueNRG2/Controller/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DSTM32L4R9xx -DUSE_HAL_DRIVER -DUSE_USB_FS -DUSE_SENSORTILEBOX -DARM_MATH_CM4 -DUSE_BLE_OUTPUT -c -I../../../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/DSP/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/SensorTile.box -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hh -I../../../../../Drivers/BSP/Components/lsm6dsox -I../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC_MSC/Inc -I../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Inc -I../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../../Middlewares/ST/STM32_MotionAC_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionAW_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionEC_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionGC_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionID_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionMC_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionPM_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionPW_Library/Inc -I../../../../../Middlewares/ST/STM32_MotionTL_Library/Inc -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/ST/BlueNRG2/Utils -I../../../../../Middlewares/ST/BlueNRG2/Controller -I../../../../../Middlewares/ST/BlueNRG2/HCI_TL -I../../../../../Middlewares/ST/BlueNRG2/includes -I"../../../../../Middlewares/ST/BlueNRG2/hci/hci_tl_patterns/Basic" -O3 -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"

clean: clean-Middlewares-2f-BlueNRG2-2f-Controller

clean-Middlewares-2f-BlueNRG2-2f-Controller:
	-$(RM) ./Middlewares/BlueNRG2/Controller/bluenrg1_gap_aci.cyclo ./Middlewares/BlueNRG2/Controller/bluenrg1_gap_aci.d ./Middlewares/BlueNRG2/Controller/bluenrg1_gap_aci.o ./Middlewares/BlueNRG2/Controller/bluenrg1_gap_aci.su ./Middlewares/BlueNRG2/Controller/bluenrg1_gatt_aci.cyclo ./Middlewares/BlueNRG2/Controller/bluenrg1_gatt_aci.d ./Middlewares/BlueNRG2/Controller/bluenrg1_gatt_aci.o ./Middlewares/BlueNRG2/Controller/bluenrg1_gatt_aci.su ./Middlewares/BlueNRG2/Controller/bluenrg1_hal_aci.cyclo ./Middlewares/BlueNRG2/Controller/bluenrg1_hal_aci.d ./Middlewares/BlueNRG2/Controller/bluenrg1_hal_aci.o ./Middlewares/BlueNRG2/Controller/bluenrg1_hal_aci.su ./Middlewares/BlueNRG2/Controller/bluenrg1_l2cap_aci.cyclo ./Middlewares/BlueNRG2/Controller/bluenrg1_l2cap_aci.d ./Middlewares/BlueNRG2/Controller/bluenrg1_l2cap_aci.o ./Middlewares/BlueNRG2/Controller/bluenrg1_l2cap_aci.su

.PHONY: clean-Middlewares-2f-BlueNRG2-2f-Controller

